/*
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class GroceryProposalProvider extends AbstractGroceryProposalProvider {
}
