/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.ui.contentassist;

import org.xtext.project439.ui.contentassist.AbstractGroceryProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GroceryProposalProvider extends AbstractGroceryProposalProvider {
}
