/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Customer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.Customer#getCustomerName <em>Customer Name</em>}</li>
 *   <li>{@link org.xtext.project439.grocery.Customer#getSale <em>Sale</em>}</li>
 * </ul>
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getCustomer()
 * @model
 * @generated
 */
public interface Customer extends Person
{
  /**
   * Returns the value of the '<em><b>Customer Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Customer Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Customer Name</em>' attribute.
   * @see #setCustomerName(String)
   * @see org.xtext.project439.grocery.GroceryPackage#getCustomer_CustomerName()
   * @model
   * @generated
   */
  String getCustomerName();

  /**
   * Sets the value of the '{@link org.xtext.project439.grocery.Customer#getCustomerName <em>Customer Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Customer Name</em>' attribute.
   * @see #getCustomerName()
   * @generated
   */
  void setCustomerName(String value);

  /**
   * Returns the value of the '<em><b>Sale</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project439.grocery.Sale}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sale</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sale</em>' reference list.
   * @see org.xtext.project439.grocery.GroceryPackage#getCustomer_Sale()
   * @model
   * @generated
   */
  EList<Sale> getSale();

} // Customer
