/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Driver</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.Driver#getDriverName <em>Driver Name</em>}</li>
 *   <li>{@link org.xtext.project439.grocery.Driver#getVehicle <em>Vehicle</em>}</li>
 * </ul>
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getDriver()
 * @model
 * @generated
 */
public interface Driver extends Person
{
  /**
   * Returns the value of the '<em><b>Driver Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Driver Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Driver Name</em>' attribute.
   * @see #setDriverName(String)
   * @see org.xtext.project439.grocery.GroceryPackage#getDriver_DriverName()
   * @model
   * @generated
   */
  String getDriverName();

  /**
   * Sets the value of the '{@link org.xtext.project439.grocery.Driver#getDriverName <em>Driver Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Driver Name</em>' attribute.
   * @see #getDriverName()
   * @generated
   */
  void setDriverName(String value);

  /**
   * Returns the value of the '<em><b>Vehicle</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project439.grocery.Vehicle}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vehicle</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vehicle</em>' reference list.
   * @see org.xtext.project439.grocery.GroceryPackage#getDriver_Vehicle()
   * @model
   * @generated
   */
  EList<Vehicle> getVehicle();

} // Driver
