/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Employee</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.Employee#getEmployeeName <em>Employee Name</em>}</li>
 *   <li>{@link org.xtext.project439.grocery.Employee#getStockMovement <em>Stock Movement</em>}</li>
 * </ul>
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getEmployee()
 * @model
 * @generated
 */
public interface Employee extends Person
{
  /**
   * Returns the value of the '<em><b>Employee Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Employee Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Employee Name</em>' attribute.
   * @see #setEmployeeName(String)
   * @see org.xtext.project439.grocery.GroceryPackage#getEmployee_EmployeeName()
   * @model
   * @generated
   */
  String getEmployeeName();

  /**
   * Sets the value of the '{@link org.xtext.project439.grocery.Employee#getEmployeeName <em>Employee Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Employee Name</em>' attribute.
   * @see #getEmployeeName()
   * @generated
   */
  void setEmployeeName(String value);

  /**
   * Returns the value of the '<em><b>Stock Movement</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project439.grocery.StockMovement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stock Movement</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stock Movement</em>' reference list.
   * @see org.xtext.project439.grocery.GroceryPackage#getEmployee_StockMovement()
   * @model
   * @generated
   */
  EList<StockMovement> getStockMovement();

} // Employee
