/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Food Item</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getFoodItem()
 * @model
 * @generated
 */
public interface FoodItem extends Item
{
} // FoodItem
