/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.project439.grocery.GroceryFactory
 * @model kind="package"
 * @generated
 */
public interface GroceryPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "grocery";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/project439/Grocery";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "grocery";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GroceryPackage eINSTANCE = org.xtext.project439.grocery.impl.GroceryPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.GroceryImpl <em>Grocery</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.GroceryImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getGrocery()
   * @generated
   */
  int GROCERY = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROCERY__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Grocery</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROCERY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.BuildingImpl <em>Building</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.BuildingImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getBuilding()
   * @generated
   */
  int BUILDING = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUILDING__NAME = 0;

  /**
   * The number of structural features of the '<em>Building</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUILDING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.StoreElementsImpl <em>Store Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.StoreElementsImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getStoreElements()
   * @generated
   */
  int STORE_ELEMENTS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_ELEMENTS__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_ELEMENTS__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Store Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_ELEMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.DeliveryElementImpl <em>Delivery Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.DeliveryElementImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getDeliveryElement()
   * @generated
   */
  int DELIVERY_ELEMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELIVERY_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Delivery Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELIVERY_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.StoreImpl <em>Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.StoreImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getStore()
   * @generated
   */
  int STORE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__NAME = BUILDING__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__ELEMENTS = BUILDING_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = BUILDING_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.WarehouseImpl <em>Warehouse</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.WarehouseImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getWarehouse()
   * @generated
   */
  int WAREHOUSE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE__NAME = BUILDING__NAME;

  /**
   * The feature id for the '<em><b>Address</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE__ADDRESS = BUILDING_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE__ELEMENTS = BUILDING_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Warehouse</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAREHOUSE_FEATURE_COUNT = BUILDING_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.ShelfImpl <em>Shelf</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.ShelfImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getShelf()
   * @generated
   */
  int SHELF = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHELF__NAME = STORE_ELEMENTS__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHELF__ELEMENTS = STORE_ELEMENTS__ELEMENTS;

  /**
   * The number of structural features of the '<em>Shelf</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHELF_FEATURE_COUNT = STORE_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.BackroomImpl <em>Backroom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.BackroomImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getBackroom()
   * @generated
   */
  int BACKROOM = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKROOM__NAME = STORE_ELEMENTS__NAME;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKROOM__ELEMENTS = STORE_ELEMENTS__ELEMENTS;

  /**
   * The number of structural features of the '<em>Backroom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKROOM_FEATURE_COUNT = STORE_ELEMENTS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.ItemImpl <em>Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.ItemImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getItem()
   * @generated
   */
  int ITEM = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__PRICE = 1;

  /**
   * The number of structural features of the '<em>Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.NonPerishableItemImpl <em>Non Perishable Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.NonPerishableItemImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getNonPerishableItem()
   * @generated
   */
  int NON_PERISHABLE_ITEM = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_PERISHABLE_ITEM__NAME = ITEM__NAME;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_PERISHABLE_ITEM__PRICE = ITEM__PRICE;

  /**
   * The number of structural features of the '<em>Non Perishable Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_PERISHABLE_ITEM_FEATURE_COUNT = ITEM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.PerishableItemImpl <em>Perishable Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.PerishableItemImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getPerishableItem()
   * @generated
   */
  int PERISHABLE_ITEM = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERISHABLE_ITEM__NAME = ITEM__NAME;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERISHABLE_ITEM__PRICE = ITEM__PRICE;

  /**
   * The feature id for the '<em><b>Experation Date</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERISHABLE_ITEM__EXPERATION_DATE = ITEM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Perishable Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERISHABLE_ITEM_FEATURE_COUNT = ITEM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.AddressImpl <em>Address</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.AddressImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getAddress()
   * @generated
   */
  int ADDRESS = 11;

  /**
   * The feature id for the '<em><b>Street</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDRESS__STREET = 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDRESS__NUMBER = 1;

  /**
   * The feature id for the '<em><b>City</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDRESS__CITY = 2;

  /**
   * The number of structural features of the '<em>Address</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDRESS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.ExperationDateImpl <em>Experation Date</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.ExperationDateImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getExperationDate()
   * @generated
   */
  int EXPERATION_DATE = 12;

  /**
   * The feature id for the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERATION_DATE__MONTH = 0;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERATION_DATE__DAY = 1;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERATION_DATE__YEAR = 2;

  /**
   * The number of structural features of the '<em>Experation Date</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERATION_DATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.DriverImpl <em>Driver</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.DriverImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getDriver()
   * @generated
   */
  int DRIVER = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRIVER__NAME = DELIVERY_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Driver Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRIVER__DRIVER_NAME = DELIVERY_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Driver</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRIVER_FEATURE_COUNT = DELIVERY_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.project439.grocery.impl.VehicleImpl <em>Vehicle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.project439.grocery.impl.VehicleImpl
   * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getVehicle()
   * @generated
   */
  int VEHICLE = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VEHICLE__NAME = DELIVERY_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Plate Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VEHICLE__PLATE_NUMBER = DELIVERY_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Vehicle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VEHICLE_FEATURE_COUNT = DELIVERY_ELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Grocery <em>Grocery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grocery</em>'.
   * @see org.xtext.project439.grocery.Grocery
   * @generated
   */
  EClass getGrocery();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project439.grocery.Grocery#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.project439.grocery.Grocery#getElements()
   * @see #getGrocery()
   * @generated
   */
  EReference getGrocery_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Building <em>Building</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Building</em>'.
   * @see org.xtext.project439.grocery.Building
   * @generated
   */
  EClass getBuilding();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.Building#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.project439.grocery.Building#getName()
   * @see #getBuilding()
   * @generated
   */
  EAttribute getBuilding_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.StoreElements <em>Store Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store Elements</em>'.
   * @see org.xtext.project439.grocery.StoreElements
   * @generated
   */
  EClass getStoreElements();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.StoreElements#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.project439.grocery.StoreElements#getName()
   * @see #getStoreElements()
   * @generated
   */
  EAttribute getStoreElements_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project439.grocery.StoreElements#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.project439.grocery.StoreElements#getElements()
   * @see #getStoreElements()
   * @generated
   */
  EReference getStoreElements_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.DeliveryElement <em>Delivery Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delivery Element</em>'.
   * @see org.xtext.project439.grocery.DeliveryElement
   * @generated
   */
  EClass getDeliveryElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.DeliveryElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.project439.grocery.DeliveryElement#getName()
   * @see #getDeliveryElement()
   * @generated
   */
  EAttribute getDeliveryElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Store <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store</em>'.
   * @see org.xtext.project439.grocery.Store
   * @generated
   */
  EClass getStore();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project439.grocery.Store#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.project439.grocery.Store#getElements()
   * @see #getStore()
   * @generated
   */
  EReference getStore_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Warehouse <em>Warehouse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Warehouse</em>'.
   * @see org.xtext.project439.grocery.Warehouse
   * @generated
   */
  EClass getWarehouse();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project439.grocery.Warehouse#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Address</em>'.
   * @see org.xtext.project439.grocery.Warehouse#getAddress()
   * @see #getWarehouse()
   * @generated
   */
  EReference getWarehouse_Address();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project439.grocery.Warehouse#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.project439.grocery.Warehouse#getElements()
   * @see #getWarehouse()
   * @generated
   */
  EReference getWarehouse_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Shelf <em>Shelf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shelf</em>'.
   * @see org.xtext.project439.grocery.Shelf
   * @generated
   */
  EClass getShelf();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Backroom <em>Backroom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Backroom</em>'.
   * @see org.xtext.project439.grocery.Backroom
   * @generated
   */
  EClass getBackroom();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Item <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item</em>'.
   * @see org.xtext.project439.grocery.Item
   * @generated
   */
  EClass getItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.Item#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.project439.grocery.Item#getName()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.Item#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Price</em>'.
   * @see org.xtext.project439.grocery.Item#getPrice()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_Price();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.NonPerishableItem <em>Non Perishable Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Non Perishable Item</em>'.
   * @see org.xtext.project439.grocery.NonPerishableItem
   * @generated
   */
  EClass getNonPerishableItem();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.PerishableItem <em>Perishable Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Perishable Item</em>'.
   * @see org.xtext.project439.grocery.PerishableItem
   * @generated
   */
  EClass getPerishableItem();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.project439.grocery.PerishableItem#getExperationDate <em>Experation Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Experation Date</em>'.
   * @see org.xtext.project439.grocery.PerishableItem#getExperationDate()
   * @see #getPerishableItem()
   * @generated
   */
  EReference getPerishableItem_ExperationDate();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Address <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Address</em>'.
   * @see org.xtext.project439.grocery.Address
   * @generated
   */
  EClass getAddress();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.Address#getStreet <em>Street</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Street</em>'.
   * @see org.xtext.project439.grocery.Address#getStreet()
   * @see #getAddress()
   * @generated
   */
  EAttribute getAddress_Street();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.Address#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.project439.grocery.Address#getNumber()
   * @see #getAddress()
   * @generated
   */
  EAttribute getAddress_Number();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.Address#getCity <em>City</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>City</em>'.
   * @see org.xtext.project439.grocery.Address#getCity()
   * @see #getAddress()
   * @generated
   */
  EAttribute getAddress_City();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.ExperationDate <em>Experation Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Experation Date</em>'.
   * @see org.xtext.project439.grocery.ExperationDate
   * @generated
   */
  EClass getExperationDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.ExperationDate#getMonth <em>Month</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Month</em>'.
   * @see org.xtext.project439.grocery.ExperationDate#getMonth()
   * @see #getExperationDate()
   * @generated
   */
  EAttribute getExperationDate_Month();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.ExperationDate#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see org.xtext.project439.grocery.ExperationDate#getDay()
   * @see #getExperationDate()
   * @generated
   */
  EAttribute getExperationDate_Day();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.ExperationDate#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.project439.grocery.ExperationDate#getYear()
   * @see #getExperationDate()
   * @generated
   */
  EAttribute getExperationDate_Year();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Driver <em>Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Driver</em>'.
   * @see org.xtext.project439.grocery.Driver
   * @generated
   */
  EClass getDriver();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.Driver#getDriverName <em>Driver Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Driver Name</em>'.
   * @see org.xtext.project439.grocery.Driver#getDriverName()
   * @see #getDriver()
   * @generated
   */
  EAttribute getDriver_DriverName();

  /**
   * Returns the meta object for class '{@link org.xtext.project439.grocery.Vehicle <em>Vehicle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vehicle</em>'.
   * @see org.xtext.project439.grocery.Vehicle
   * @generated
   */
  EClass getVehicle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.project439.grocery.Vehicle#getPlateNumber <em>Plate Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Plate Number</em>'.
   * @see org.xtext.project439.grocery.Vehicle#getPlateNumber()
   * @see #getVehicle()
   * @generated
   */
  EAttribute getVehicle_PlateNumber();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GroceryFactory getGroceryFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.GroceryImpl <em>Grocery</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.GroceryImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getGrocery()
     * @generated
     */
    EClass GROCERY = eINSTANCE.getGrocery();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROCERY__ELEMENTS = eINSTANCE.getGrocery_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.BuildingImpl <em>Building</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.BuildingImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getBuilding()
     * @generated
     */
    EClass BUILDING = eINSTANCE.getBuilding();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUILDING__NAME = eINSTANCE.getBuilding_Name();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.StoreElementsImpl <em>Store Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.StoreElementsImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getStoreElements()
     * @generated
     */
    EClass STORE_ELEMENTS = eINSTANCE.getStoreElements();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE_ELEMENTS__NAME = eINSTANCE.getStoreElements_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORE_ELEMENTS__ELEMENTS = eINSTANCE.getStoreElements_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.DeliveryElementImpl <em>Delivery Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.DeliveryElementImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getDeliveryElement()
     * @generated
     */
    EClass DELIVERY_ELEMENT = eINSTANCE.getDeliveryElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DELIVERY_ELEMENT__NAME = eINSTANCE.getDeliveryElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.StoreImpl <em>Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.StoreImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getStore()
     * @generated
     */
    EClass STORE = eINSTANCE.getStore();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORE__ELEMENTS = eINSTANCE.getStore_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.WarehouseImpl <em>Warehouse</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.WarehouseImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getWarehouse()
     * @generated
     */
    EClass WAREHOUSE = eINSTANCE.getWarehouse();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WAREHOUSE__ADDRESS = eINSTANCE.getWarehouse_Address();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WAREHOUSE__ELEMENTS = eINSTANCE.getWarehouse_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.ShelfImpl <em>Shelf</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.ShelfImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getShelf()
     * @generated
     */
    EClass SHELF = eINSTANCE.getShelf();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.BackroomImpl <em>Backroom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.BackroomImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getBackroom()
     * @generated
     */
    EClass BACKROOM = eINSTANCE.getBackroom();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.ItemImpl <em>Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.ItemImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getItem()
     * @generated
     */
    EClass ITEM = eINSTANCE.getItem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__NAME = eINSTANCE.getItem_Name();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__PRICE = eINSTANCE.getItem_Price();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.NonPerishableItemImpl <em>Non Perishable Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.NonPerishableItemImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getNonPerishableItem()
     * @generated
     */
    EClass NON_PERISHABLE_ITEM = eINSTANCE.getNonPerishableItem();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.PerishableItemImpl <em>Perishable Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.PerishableItemImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getPerishableItem()
     * @generated
     */
    EClass PERISHABLE_ITEM = eINSTANCE.getPerishableItem();

    /**
     * The meta object literal for the '<em><b>Experation Date</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERISHABLE_ITEM__EXPERATION_DATE = eINSTANCE.getPerishableItem_ExperationDate();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.AddressImpl <em>Address</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.AddressImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getAddress()
     * @generated
     */
    EClass ADDRESS = eINSTANCE.getAddress();

    /**
     * The meta object literal for the '<em><b>Street</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDRESS__STREET = eINSTANCE.getAddress_Street();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDRESS__NUMBER = eINSTANCE.getAddress_Number();

    /**
     * The meta object literal for the '<em><b>City</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDRESS__CITY = eINSTANCE.getAddress_City();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.ExperationDateImpl <em>Experation Date</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.ExperationDateImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getExperationDate()
     * @generated
     */
    EClass EXPERATION_DATE = eINSTANCE.getExperationDate();

    /**
     * The meta object literal for the '<em><b>Month</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPERATION_DATE__MONTH = eINSTANCE.getExperationDate_Month();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPERATION_DATE__DAY = eINSTANCE.getExperationDate_Day();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPERATION_DATE__YEAR = eINSTANCE.getExperationDate_Year();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.DriverImpl <em>Driver</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.DriverImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getDriver()
     * @generated
     */
    EClass DRIVER = eINSTANCE.getDriver();

    /**
     * The meta object literal for the '<em><b>Driver Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRIVER__DRIVER_NAME = eINSTANCE.getDriver_DriverName();

    /**
     * The meta object literal for the '{@link org.xtext.project439.grocery.impl.VehicleImpl <em>Vehicle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.project439.grocery.impl.VehicleImpl
     * @see org.xtext.project439.grocery.impl.GroceryPackageImpl#getVehicle()
     * @generated
     */
    EClass VEHICLE = eINSTANCE.getVehicle();

    /**
     * The meta object literal for the '<em><b>Plate Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VEHICLE__PLATE_NUMBER = eINSTANCE.getVehicle_PlateNumber();

  }

} //GroceryPackage
