/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grocery</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.Grocery#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getGrocery()
 * @model
 * @generated
 */
public interface Grocery extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.project439.grocery.AbstractElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xtext.project439.grocery.GroceryPackage#getGrocery_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractElement> getElements();

} // Grocery
