/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Produce</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.Produce#getQuality <em>Quality</em>}</li>
 * </ul>
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getProduce()
 * @model
 * @generated
 */
public interface Produce extends FoodItem
{
  /**
   * Returns the value of the '<em><b>Quality</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.project439.grocery.qualityLevel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Quality</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quality</em>' attribute.
   * @see org.xtext.project439.grocery.qualityLevel
   * @see #setQuality(qualityLevel)
   * @see org.xtext.project439.grocery.GroceryPackage#getProduce_Quality()
   * @model
   * @generated
   */
  qualityLevel getQuality();

  /**
   * Sets the value of the '{@link org.xtext.project439.grocery.Produce#getQuality <em>Quality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quality</em>' attribute.
   * @see org.xtext.project439.grocery.qualityLevel
   * @see #getQuality()
   * @generated
   */
  void setQuality(qualityLevel value);

} // Produce
