/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shelf</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getShelf()
 * @model
 * @generated
 */
public interface Shelf extends StoreElements
{
} // Shelf
