/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stock Movement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.StockMovement#getFromBackroom <em>From Backroom</em>}</li>
 *   <li>{@link org.xtext.project439.grocery.StockMovement#getToShelf <em>To Shelf</em>}</li>
 * </ul>
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getStockMovement()
 * @model
 * @generated
 */
public interface StockMovement extends Movement
{
  /**
   * Returns the value of the '<em><b>From Backroom</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From Backroom</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From Backroom</em>' reference.
   * @see #setFromBackroom(Backroom)
   * @see org.xtext.project439.grocery.GroceryPackage#getStockMovement_FromBackroom()
   * @model
   * @generated
   */
  Backroom getFromBackroom();

  /**
   * Sets the value of the '{@link org.xtext.project439.grocery.StockMovement#getFromBackroom <em>From Backroom</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From Backroom</em>' reference.
   * @see #getFromBackroom()
   * @generated
   */
  void setFromBackroom(Backroom value);

  /**
   * Returns the value of the '<em><b>To Shelf</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To Shelf</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Shelf</em>' reference.
   * @see #setToShelf(Shelf)
   * @see org.xtext.project439.grocery.GroceryPackage#getStockMovement_ToShelf()
   * @model
   * @generated
   */
  Shelf getToShelf();

  /**
   * Sets the value of the '{@link org.xtext.project439.grocery.StockMovement#getToShelf <em>To Shelf</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Shelf</em>' reference.
   * @see #getToShelf()
   * @generated
   */
  void setToShelf(Shelf value);

} // StockMovement
