/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Store Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.StoreElements#getItems <em>Items</em>}</li>
 * </ul>
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getStoreElements()
 * @model
 * @generated
 */
public interface StoreElements extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Items</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project439.grocery.Item}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' reference list.
   * @see org.xtext.project439.grocery.GroceryPackage#getStoreElements_Items()
   * @model
   * @generated
   */
  EList<Item> getItems();

} // StoreElements
