/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vehicle Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getVehicleElements()
 * @model
 * @generated
 */
public interface VehicleElements extends EObject
{
} // VehicleElements
