/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vehicle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.Vehicle#getPlateNumber <em>Plate Number</em>}</li>
 *   <li>{@link org.xtext.project439.grocery.Vehicle#getDelivery <em>Delivery</em>}</li>
 * </ul>
 *
 * @see org.xtext.project439.grocery.GroceryPackage#getVehicle()
 * @model
 * @generated
 */
public interface Vehicle extends MovementElement
{
  /**
   * Returns the value of the '<em><b>Plate Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plate Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plate Number</em>' attribute.
   * @see #setPlateNumber(String)
   * @see org.xtext.project439.grocery.GroceryPackage#getVehicle_PlateNumber()
   * @model
   * @generated
   */
  String getPlateNumber();

  /**
   * Sets the value of the '{@link org.xtext.project439.grocery.Vehicle#getPlateNumber <em>Plate Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plate Number</em>' attribute.
   * @see #getPlateNumber()
   * @generated
   */
  void setPlateNumber(String value);

  /**
   * Returns the value of the '<em><b>Delivery</b></em>' reference list.
   * The list contents are of type {@link org.xtext.project439.grocery.Delivery}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Delivery</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delivery</em>' reference list.
   * @see org.xtext.project439.grocery.GroceryPackage#getVehicle_Delivery()
   * @model
   * @generated
   */
  EList<Delivery> getDelivery();

} // Vehicle
