/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.project439.GroceryRuntimeModule;
import org.xtext.project439.GroceryStandaloneSetup;
import org.xtext.project439.ide.GroceryIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GroceryIdeSetup extends GroceryStandaloneSetup {
  @Override
  public Injector createInjector() {
    GroceryRuntimeModule _groceryRuntimeModule = new GroceryRuntimeModule();
    GroceryIdeModule _groceryIdeModule = new GroceryIdeModule();
    return Guice.createInjector(Modules2.mixin(_groceryRuntimeModule, _groceryIdeModule));
  }
}
