/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.ide;

import org.xtext.project439.ide.AbstractGroceryIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GroceryIdeModule extends AbstractGroceryIdeModule {
}
