/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.project439.grocery.Delivery;
import org.xtext.project439.grocery.GroceryPackage;
import org.xtext.project439.grocery.Store;
import org.xtext.project439.grocery.Warehouse;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Delivery</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.impl.DeliveryImpl#getFromWarehouse <em>From Warehouse</em>}</li>
 *   <li>{@link org.xtext.project439.grocery.impl.DeliveryImpl#getToStore <em>To Store</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeliveryImpl extends MovementImpl implements Delivery
{
  /**
   * The cached value of the '{@link #getFromWarehouse() <em>From Warehouse</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFromWarehouse()
   * @generated
   * @ordered
   */
  protected Warehouse fromWarehouse;

  /**
   * The cached value of the '{@link #getToStore() <em>To Store</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getToStore()
   * @generated
   * @ordered
   */
  protected Store toStore;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeliveryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GroceryPackage.Literals.DELIVERY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Warehouse getFromWarehouse()
  {
    if (fromWarehouse != null && fromWarehouse.eIsProxy())
    {
      InternalEObject oldFromWarehouse = (InternalEObject)fromWarehouse;
      fromWarehouse = (Warehouse)eResolveProxy(oldFromWarehouse);
      if (fromWarehouse != oldFromWarehouse)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GroceryPackage.DELIVERY__FROM_WAREHOUSE, oldFromWarehouse, fromWarehouse));
      }
    }
    return fromWarehouse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Warehouse basicGetFromWarehouse()
  {
    return fromWarehouse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFromWarehouse(Warehouse newFromWarehouse)
  {
    Warehouse oldFromWarehouse = fromWarehouse;
    fromWarehouse = newFromWarehouse;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GroceryPackage.DELIVERY__FROM_WAREHOUSE, oldFromWarehouse, fromWarehouse));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Store getToStore()
  {
    if (toStore != null && toStore.eIsProxy())
    {
      InternalEObject oldToStore = (InternalEObject)toStore;
      toStore = (Store)eResolveProxy(oldToStore);
      if (toStore != oldToStore)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GroceryPackage.DELIVERY__TO_STORE, oldToStore, toStore));
      }
    }
    return toStore;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Store basicGetToStore()
  {
    return toStore;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setToStore(Store newToStore)
  {
    Store oldToStore = toStore;
    toStore = newToStore;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GroceryPackage.DELIVERY__TO_STORE, oldToStore, toStore));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GroceryPackage.DELIVERY__FROM_WAREHOUSE:
        if (resolve) return getFromWarehouse();
        return basicGetFromWarehouse();
      case GroceryPackage.DELIVERY__TO_STORE:
        if (resolve) return getToStore();
        return basicGetToStore();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GroceryPackage.DELIVERY__FROM_WAREHOUSE:
        setFromWarehouse((Warehouse)newValue);
        return;
      case GroceryPackage.DELIVERY__TO_STORE:
        setToStore((Store)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GroceryPackage.DELIVERY__FROM_WAREHOUSE:
        setFromWarehouse((Warehouse)null);
        return;
      case GroceryPackage.DELIVERY__TO_STORE:
        setToStore((Store)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GroceryPackage.DELIVERY__FROM_WAREHOUSE:
        return fromWarehouse != null;
      case GroceryPackage.DELIVERY__TO_STORE:
        return toStore != null;
    }
    return super.eIsSet(featureID);
  }

} //DeliveryImpl
