/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.project439.grocery.FoodItem;
import org.xtext.project439.grocery.GroceryPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Food Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FoodItemImpl extends ItemImpl implements FoodItem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FoodItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GroceryPackage.Literals.FOOD_ITEM;
  }

} //FoodItemImpl
