/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.project439.grocery.ExperationDate;
import org.xtext.project439.grocery.GroceryPackage;
import org.xtext.project439.grocery.PerishableItem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Perishable Item</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.impl.PerishableItemImpl#getExperationDate <em>Experation Date</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PerishableItemImpl extends ItemImpl implements PerishableItem
{
  /**
   * The cached value of the '{@link #getExperationDate() <em>Experation Date</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExperationDate()
   * @generated
   * @ordered
   */
  protected EList<ExperationDate> experationDate;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PerishableItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GroceryPackage.Literals.PERISHABLE_ITEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ExperationDate> getExperationDate()
  {
    if (experationDate == null)
    {
      experationDate = new EObjectContainmentEList<ExperationDate>(ExperationDate.class, this, GroceryPackage.PERISHABLE_ITEM__EXPERATION_DATE);
    }
    return experationDate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GroceryPackage.PERISHABLE_ITEM__EXPERATION_DATE:
        return ((InternalEList<?>)getExperationDate()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GroceryPackage.PERISHABLE_ITEM__EXPERATION_DATE:
        return getExperationDate();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GroceryPackage.PERISHABLE_ITEM__EXPERATION_DATE:
        getExperationDate().clear();
        getExperationDate().addAll((Collection<? extends ExperationDate>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GroceryPackage.PERISHABLE_ITEM__EXPERATION_DATE:
        getExperationDate().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GroceryPackage.PERISHABLE_ITEM__EXPERATION_DATE:
        return experationDate != null && !experationDate.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //PerishableItemImpl
