/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.project439.grocery.GroceryPackage;
import org.xtext.project439.grocery.VehicleElements;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Vehicle Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VehicleElementsImpl extends MinimalEObjectImpl.Container implements VehicleElements
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VehicleElementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GroceryPackage.Literals.VEHICLE_ELEMENTS;
  }

} //VehicleElementsImpl
