/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.project439.grocery.Delivery;
import org.xtext.project439.grocery.GroceryPackage;
import org.xtext.project439.grocery.Vehicle;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Vehicle</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.impl.VehicleImpl#getPlateNumber <em>Plate Number</em>}</li>
 *   <li>{@link org.xtext.project439.grocery.impl.VehicleImpl#getDelivery <em>Delivery</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VehicleImpl extends MovementElementImpl implements Vehicle
{
  /**
   * The default value of the '{@link #getPlateNumber() <em>Plate Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlateNumber()
   * @generated
   * @ordered
   */
  protected static final String PLATE_NUMBER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPlateNumber() <em>Plate Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlateNumber()
   * @generated
   * @ordered
   */
  protected String plateNumber = PLATE_NUMBER_EDEFAULT;

  /**
   * The cached value of the '{@link #getDelivery() <em>Delivery</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDelivery()
   * @generated
   * @ordered
   */
  protected EList<Delivery> delivery;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VehicleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GroceryPackage.Literals.VEHICLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPlateNumber()
  {
    return plateNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPlateNumber(String newPlateNumber)
  {
    String oldPlateNumber = plateNumber;
    plateNumber = newPlateNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GroceryPackage.VEHICLE__PLATE_NUMBER, oldPlateNumber, plateNumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Delivery> getDelivery()
  {
    if (delivery == null)
    {
      delivery = new EObjectResolvingEList<Delivery>(Delivery.class, this, GroceryPackage.VEHICLE__DELIVERY);
    }
    return delivery;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GroceryPackage.VEHICLE__PLATE_NUMBER:
        return getPlateNumber();
      case GroceryPackage.VEHICLE__DELIVERY:
        return getDelivery();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GroceryPackage.VEHICLE__PLATE_NUMBER:
        setPlateNumber((String)newValue);
        return;
      case GroceryPackage.VEHICLE__DELIVERY:
        getDelivery().clear();
        getDelivery().addAll((Collection<? extends Delivery>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GroceryPackage.VEHICLE__PLATE_NUMBER:
        setPlateNumber(PLATE_NUMBER_EDEFAULT);
        return;
      case GroceryPackage.VEHICLE__DELIVERY:
        getDelivery().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GroceryPackage.VEHICLE__PLATE_NUMBER:
        return PLATE_NUMBER_EDEFAULT == null ? plateNumber != null : !PLATE_NUMBER_EDEFAULT.equals(plateNumber);
      case GroceryPackage.VEHICLE__DELIVERY:
        return delivery != null && !delivery.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (plateNumber: ");
    result.append(plateNumber);
    result.append(')');
    return result.toString();
  }

} //VehicleImpl
