/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project439.grocery.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.project439.grocery.Address;
import org.xtext.project439.grocery.GroceryPackage;
import org.xtext.project439.grocery.Item;
import org.xtext.project439.grocery.Warehouse;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Warehouse</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project439.grocery.impl.WarehouseImpl#getAddress <em>Address</em>}</li>
 *   <li>{@link org.xtext.project439.grocery.impl.WarehouseImpl#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WarehouseImpl extends BuildingImpl implements Warehouse
{
  /**
   * The cached value of the '{@link #getAddress() <em>Address</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAddress()
   * @generated
   * @ordered
   */
  protected EList<Address> address;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<Item> elements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WarehouseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GroceryPackage.Literals.WAREHOUSE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Address> getAddress()
  {
    if (address == null)
    {
      address = new EObjectContainmentEList<Address>(Address.class, this, GroceryPackage.WAREHOUSE__ADDRESS);
    }
    return address;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Item> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<Item>(Item.class, this, GroceryPackage.WAREHOUSE__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GroceryPackage.WAREHOUSE__ADDRESS:
        return ((InternalEList<?>)getAddress()).basicRemove(otherEnd, msgs);
      case GroceryPackage.WAREHOUSE__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GroceryPackage.WAREHOUSE__ADDRESS:
        return getAddress();
      case GroceryPackage.WAREHOUSE__ELEMENTS:
        return getElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GroceryPackage.WAREHOUSE__ADDRESS:
        getAddress().clear();
        getAddress().addAll((Collection<? extends Address>)newValue);
        return;
      case GroceryPackage.WAREHOUSE__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends Item>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GroceryPackage.WAREHOUSE__ADDRESS:
        getAddress().clear();
        return;
      case GroceryPackage.WAREHOUSE__ELEMENTS:
        getElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GroceryPackage.WAREHOUSE__ADDRESS:
        return address != null && !address.isEmpty();
      case GroceryPackage.WAREHOUSE__ELEMENTS:
        return elements != null && !elements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //WarehouseImpl
